In [7]:
number_list=[5,8,2,4,7,9];
print (sum(number_list));

35


In [10]:
def multiply(numList):
    theSum = 1
    for i in numList:
        theSum = theSum * i
    return theSum
number_list=[4,3,5,6,2];
print (multiply(number_list));

720


In [38]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw);
print (np.sort(array_hw, axis=None));
print (array_hw[...,1])
print (np.sort(array_hw[2,]));
print (array_hw[1:,...]);
print (array_hw[...,2:]);
print (np.square(array_hw));
print (array_hw[2,3]);
print (np.sum(array_hw));
print (array_hw.ndim);

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]
[5 7 7 9]
[2 4 6 7 8 8]
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]
[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]
4
145
2
